name: Deploy Test Report

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install gh-pages
        run: npm install -g gh-pages

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p reports
          cp -r test-output/* reports/
          touch reports/.nojekyll
          gh-pages -d reports -t true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 